FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY ../source-code/external-api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY ../source-code/external-api/ .

# Expose port
EXPOSE 8080

# Start application
CMD ["python", "app.py"]